server:
  port: 7688

spring:
  application:
    name: JavaMethod
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        # 默认数据源
        master:
          url: jdbc:mysql://127.0.0.1:3306/javamethod?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    # 引入其他yml配置
    active: druid
  # redis 配置
  redis:
    # 地址
    host: 123.57.51.130
    # 端口，默认为6379
    port: 6379
  # rabbitmq 配置
  rabbitmq:
    host: 123.57.51.130
    port: 5672
    username: root
    password: root
  # 配置swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  swagger:
    enabled: true
    title: 用户接口文档
    description: 用户接口文档
    version: 1.0
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
