# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

obtain:
  ymlfile:
    values: '使用注解获取yml文件参数值'
    # 定时任务执行时间（秒）
    time: 60
    logPath: 'D:\home\JavaMethod\logs\'

splitKey: '&&'
nThreads: 10
# elasticsearch日志级别配置
logging:
  level:
    cn:
      tedu:
        search: debug
    org:
      elasticsearch:
        client:
          RestClient: debug
elasticsearch:
  rest:
    uris: 127.0.0.1:9200
    connection-timeout: 1s
    read-timeout: 30s