server:
  port: 7688
spring:
  application:
    name: JavaMethod
  # activemq
  activemq:
    broker-url: tcp://123.57.51.130:61617
    user: root
    password: root
  # 数据源配置
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        # 默认数据源
        master:
          url: jdbc:mysql://127.0.0.1:3306/javamethod?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

  #elasticsearch
  elasticsearch:
    uris: https://127.0.0.1:9200
  profiles:
    # 引入其他yml配置
    active: druid
  # redis 配置
  redis:
    # 地址
    host: 123.57.51.130
    # 端口，默认为6379
    port: 6379
    password: root
  # rabbitmq 配置
  rabbitmq:
    host: 123.57.51.130
    port: 5672
    username: root
    password: root
    listener:
      simple:
        acknowledge-mode: MANUAL
  # 配置swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  swagger:
    enabled: true
    title: 用户接口文档
    description: 用户接口文档
    version: 1.0
  # 配置安全认证信息 对登录的用户名/密码进行配置
  security:
    user:
      name: root
      password: root
  # 配置thymeleaf模板引擎 websocket配置
  thymeleaf:
    mode: HTML
    cache: true
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    template-resolver-order: 1